/**
 * Privacy Policy page — accurate to what this app actually does.
 * No generic boilerplate. No fabricated compliance claims.
 */

import LegalLayout from '../components/LegalLayout';

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="July 2025">
      <p>
        SEO Operating System (&quot;SEO OS&quot;, &quot;we&quot;, &quot;us&quot;) is an AI-powered SEO platform. This
        policy explains what data we collect, how we use it, and your choices. We wrote it to be honest and specific to
        our product — not filled with legal jargon that doesn&apos;t apply.
      </p>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">What data we collect</h2>

      <h3 className="font-heading text-cream/90 mb-1 text-sm font-semibold">Account information</h3>
      <p>
        When you register, we store your <strong>email address</strong>, <strong>name</strong>, and a{' '}
        <strong>bcrypt-hashed password</strong>. We do not store your password in plain text — ever. Your email is used
        as your login identifier and for account-related notifications.
      </p>

      <h3 className="font-heading text-cream/90 mt-4 mb-1 text-sm font-semibold">Site and audit data</h3>
      <p>
        When you add a site to a workspace, we store the <strong>domain URL</strong> you provide. When you run an audit,
        keyword research, content review, or competitor analysis, the results are stored in our database so you can view
        them later. This includes crawled page data, technical SEO issues, keyword clusters, and AI-generated
        suggestions.
      </p>

      <h3 className="font-heading text-cream/90 mt-4 mb-1 text-sm font-semibold">Google Search Console data</h3>
      <p>
        If you connect Google Search Console, we store an <strong>AES-256-CBC encrypted refresh token</strong> — never
        the plaintext token. We use this token to fetch search analytics data (query positions, clicks, impressions) for
        your site via the official Google Search Console API. You can disconnect at any time, which deletes the
        encrypted token from our database.
      </p>

      <h3 className="font-heading text-cream/90 mt-4 mb-1 text-sm font-semibold">AI processing</h3>
      <p>
        Keyword research, content reviews, competitor gap analysis, and action plans are generated by sending your data
        to the Groq API. We do not train models on your data. Groq&apos;s data handling is governed by their own privacy
        policy at{' '}
        <a
          href="https://groq.com/privacy-policy"
          target="_blank"
          rel="noopener noreferrer"
          className="text-clay hover:text-clay/80 underline underline-offset-2"
        >
          groq.com
        </a>
        .
      </p>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">How we use your data</h2>
      <ul className="list-inside list-disc space-y-2">
        <li>To provide the SEO analysis and reporting features of the platform</li>
        <li>To authenticate you and maintain your workspace</li>
        <li>To send workspace-scoped notifications (e.g. audit complete, action plan ready)</li>
        <li>To fetch and display Google Search Console data you&apos;ve authorised</li>
      </ul>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">What we don&apos;t do with your data</h2>
      <ul className="list-inside list-disc space-y-2">
        <li>
          We do <strong>not sell</strong> your data to third parties
        </li>
        <li>
          We do <strong>not share</strong> your data with advertisers
        </li>
        <li>
          We do <strong>not use</strong> your data for purposes unrelated to the platform
        </li>
        <li>
          We do <strong>not scrape</strong> Google SERPs or any platform that prohibits automated access
        </li>
      </ul>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Cookies and local storage</h2>
      <p>
        We use <strong>essential-only cookies and local storage</strong>. No third-party advertising or tracking
        cookies. Specifically:
      </p>
      <ul className="list-inside list-disc space-y-2">
        <li>
          <strong>Authentication token</strong> — stored in browser memory (Zustand store, not a cookie). The token is
          lost on page refresh, requiring re-login. We do not use persistent cookies for auth.
        </li>
        <li>
          <strong>No analytics cookies</strong> — we do not currently run Google Analytics, Mixpanel, or any third-party
          tracking.
        </li>
      </ul>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Data retention and deletion</h2>
      <p>
        Your data is retained as long as your account is active. To request account deletion and removal of all
        associated data, contact us at{' '}
        <a href="mailto:support@seo-os.com" className="text-clay hover:text-clay/80 underline underline-offset-2">
          support@seo-os.com
        </a>
        . We will delete your account, workspaces, sites, and all associated data within 30 days of a verified request.
      </p>
      <p>Notifications are automatically deleted after 30 days via a MongoDB TTL index.</p>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Data security</h2>
      <p>
        We take reasonable measures to protect your data. Passwords are hashed with bcrypt (12 rounds). GSC refresh
        tokens are encrypted at rest with AES-256-CBC. JWT tokens are used for stateless authentication. Environment
        secrets are never exposed to the client. See our{' '}
        <a href="/security" className="text-clay hover:text-clay/80 underline underline-offset-2">
          Security page
        </a>{' '}
        for more detail.
      </p>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Third-party services</h2>
      <ul className="list-inside list-disc space-y-2">
        <li>
          <strong>MongoDB Atlas</strong> — database hosting. Data is encrypted in transit and at rest by MongoDB.
        </li>
        <li>
          <strong>Groq API</strong> — AI inference for keyword research, content analysis, and action plans.
        </li>
        <li>
          <strong>Google OAuth2 / Search Console API</strong> — rank tracking data, accessed only with your explicit
          authorisation.
        </li>
      </ul>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Changes to this policy</h2>
      <p>
        We may update this policy as our product evolves. We&apos;ll note the &quot;Last updated&quot; date at the top.
        Continued use of the platform after changes constitutes acceptance of the updated policy.
      </p>

      <h2 className="font-heading text-cream mt-8 mb-3 text-lg font-semibold">Contact</h2>
      <p>
        Questions about this policy? Reach us at{' '}
        <a href="mailto:support@seo-os.com" className="text-clay hover:text-clay/80 underline underline-offset-2">
          support@seo-os.com
        </a>
        .
      </p>
    </LegalLayout>
  );
}
